# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron: "0 */2 * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run update-readme
    - uses: actions/checkout@v3
    - run: |
          git config user.name dapier
          git config user.email josuea501@gmail.com 
          git add README.md
          git commit -m "[bot] README updated with latest info"
          git push origin main
